- Quran.xcodeproj/project.pbxproj
- Quran/AyahInfo.swift
- Quran/AyahInfoPersistenceStorage.swift
- Quran/AyahNumber.swift
- Quran/CGRect+Extension.swift
- Quran/HighlightingView.swift
- Quran/QuranPageCollectionViewCell.swift
- Quran/QuranPagesDataSource.swift
- Quran/QuranViewController.swift
- Quran/SQLiteAyahInfoRetriever.swift
This patch consists of two parts - first, normalizing the results that
come back from the database so that they appear consistent per line
(since the database stores positions per word). Second, it implements
the HighlightingView so that verses can be highlighted.
> Support highlighting a particular ayah

- Quran/tr.lproj/Localizable.strings
Changed English text to Turkish,
Translated by Ismail Uslu
PR by Abdelouali Benkheil
> Update turkish Localizable.strings

- Quran/QuranPagesDataSource.swift
Fixes #48. I think in iOS 10, they load multiple cells at once, so I added `willDispalyCell` to configure the highlighting.
> Fix the highlighting issue when the collection view scrolls

- Quran/AyahBookmarkDataSource.swift
- Quran/AyahNumber.swift
- Quran/Juz.swift
- Quran/JuzBasedLastAyahFinder.swift
- Quran/JuzsMutlipleSectionDataSource.swift
- Quran/LastPageBookmarkDataSource.swift
- Quran/PageBasedLastAyahFinder.swift
- Quran/PageBookmarkDataSource.swift
- Quran/Quran.swift
- Quran/QuranPage.swift
- Quran/QuranPagesDataRetriever.swift
- Quran/QuranUtilities.swift
- Quran/Sura.swift
- Quran/SurasDataSource.swift
> Fix for the last ayah finder algorithm

- Quran/QueuePlayer.swift
- Quran/QuranPagesDataSource.swift
- Quran/QuranViewController.swift
> Fix for the app changing current page when in background + Shortening Notification Names

- Quran/AyahTextPersistenceStorage.swift
- Quran/ConnectionsPool.swift
- Quran/Crash.swift
- Quran/DefaultAyahInfoRetriever.swift
- Quran/LazyConnectionWrapper.swift
- Quran/PersistenceError.swift
- Quran/SQLiteAyahInfoPersistence.swift
- Quran/SQLiteAyahTimingPersistence.swift
- Quran/SQLiteLastPagesPersistence.swift
- Quran/SQLitePersistence.swift
- Quran/SessionDelegate.swift
> Fix for the updating last pages

- LICENSE
- README.md
Still, need to update all source code files to add a header with a short license description.
Also, we need to add a Swiftlint rule file_header.
> Change project license to GPLv3.

- Quran/QuranShareData.swift
- Quran/QuranView.swift
- Quran/QuranViewController.swift
- Quran/ShareController/ShareController.swift
> Fixes a crash when user tries to share a verse on iPad devices

- Quran/Info.plist
- Quran/QuranBaseBasicDataSource.swift
- Quran/QuranBasePageCollectionViewCell.swift
- Quran/QuranBasicDataSourceRepresentable.swift
- Quran/QuranDataSource.swift
- Quran/QuranImagePageCollectionViewCell.swift
- Quran/QuranTranslationCollectionPageCollectionViewCell.swift
- Quran/QuranViewController.swift
- Quran/ScrollViewPageBehavior.swift
Fixes #110 
And also setting `ITSAppUsesNonExemptEncryption` to `false` in Info.plist so that we are not asked about it every time we submit a release.
> Using scrollViewWillBeginDragging to dismiss the bars

- Quran/BaseNavigationController.swift
- Quran/BasePageSelectionViewController.swift
- Quran/BaseTableBasedViewController.swift
- Quran/Info.plist
- Quran/MainTabBarController.swift
- Quran/QuranBaseBasicDataSource.swift
- Quran/QuranBasePageCollectionViewCell.swift
- Quran/QuranBasicDataSourceRepresentable.swift
- Quran/QuranDataSource.swift
- Quran/QuranImagePageCollectionViewCell.swift
- Quran/QuranTranslationCollectionPageCollectionViewCell.swift
- Quran/QuranViewController.swift
- Quran/ScrollViewPageBehavior.swift
- Quran/TranslationsDataSource.swift
- Quran/TranslationsViewController.swift
> Fixes for TabBar scrolling & Edit/Done behavior for Translations

- Quran/QuranView.swift
Assalamualaykum, this is a fix for issue #204
> Prevent long tap gesture on audio bottom bar

- Quran.xcodeproj/project.pbxproj
- Quran/AppDelegate.swift
- Quran/Container.swift
- Quran/Review.swift
- Quran/UserDefaults+Keys.swift
Check for app install date and number of counts app opened, then ask for Review and Rating.
This should close #214
> Added review controller

- Quran/QuranView.swift
- Quran/QuranViewController.swift
- UIKitExtension/UIImage+Extension.swift
Fixes https://github.com/quran/quran-ios/issues/89
> Start audio from specific verse

- README.md
Update Readme for the proper setup of project.
> Update Readme.md for proper setup

- Quran/SearchService.swift
Fixes #162 
Give the user the ability to search for ayah as in `12:2` or just the beginning of a sura as in `4`.
> Search by ayah number or sura number

- Quran/Localizations.swift
- Quran/QuranFoundation+Extensions.swift
- Quran/SQLiteAyahTextPersistence.swift
Fixes #261 
Users can search for sura names and get autocompletion for them and the user can get results in Arabic even if the device's language is not set to Arabic.
> Search for sura names

- Quran/Search.swift
- Quran/SearchService.swift
> 270: Remove Autocompletion Duplication

- Quran/SearchService.swift
Fixes #264 
Now when a user enters 1 number, we show results for the sura, juz', hizb, and page, if applicable (i.e. if the number within the valid range).
> 264: Search for Page Number, Juz' Number & Hizb Number

- Quran.xcodeproj/project.pbxproj
- Quran/Analytics.swift
- Quran/AppDelegate.swift
- Quran/Base.lproj/Localizable.strings
- Quran/DarkThemeUpdater.swift
- Quran/UpdateHandler.swift
- Quran/ar.lproj/Localizable.strings
Fixes #275 
Added a dialog to show existing users they can turn on the dark theme. Since the dark theme is the most requested feature right now.
> 275: Update dialog to turn on dark theme

- Quran.xcodeproj/project.pbxproj
- Quran/QuranImagePageCollectionViewCell.xib
- Quran/ThemedCollectionView.swift
- Quran/ThemedScrollView.swift
- Quran/ThemedTableView.swift
> 278: Theming scroll view bar indicators

- Quran/QuranImagePageCollectionViewCell.swift
- Quran/QuranImagePageCollectionViewCell.xib
- Quran/QuranTranslationBaseCollectionViewCell.swift
- Quran/QuranTranslationCollectionPageCollectionViewCell.swift
- Quran/QuranView.swift
- Quran/QuranViewController.swift
- Quran/Theme+extensions.swift
- Quran/ThemedCollectionViewCell.swift
- Quran/UIColor+Theme.swift
Fixes #297 
Fixes #299 
Refer to commit messages.
> OptimIzed for OLED Screens

- Quran/SQLiteSearchableAyahTextPersistence.swift
This patch improves Arabic search by fuzzily replacing certain
characters with a set of other acceptable ones (ex ا should match أ, إ,
etc). This works by switching the Arabic SQL query with a like query,
replacing these characters with an _. It then postprocesses them,
filtering out the ones that match the pattern with a character that is
unrelated to the one that was searched with.
> Improve Arabic search

- Sources/BatchDownloader/Downloader/DownloadBatchDataController.swift
- Sources/BatchDownloader/Downloader/DownloadSessionDelegate.swift
- Sources/BatchDownloader/Entities/DownloadBatchResponse.swift
As URLSession completes using another subclass of URLSessionTask other than URLSessionDownloadTask.
> Fix bug when session completes but not persistence

- Sources/QuranAudioKit/AudioPlayer/GaplessAudioRequestBuilder.swift
- Sources/QuranAudioKit/Timing/AyahTiming.swift
- Sources/QuranAudioKit/Timing/AyahTimingPersistence.swift
- Sources/QuranAudioKit/Timing/ReciterTimingRetriever.swift
- Tests/QuranAudioKitTests/QuranAudioPlayerTests.swift
- Tests/QuranAudioKitTests/__Snapshots__/QuranAudioPlayerTests/testPlayingDownloadedGaplessReciter1SurasHasEndTimestamp.1.json
- Tests/QuranAudioKitTests/__Snapshots__/QuranAudioPlayerTests/testPlayingDownloadedGaplessReciter1SurasHasEndTimestampStopBeforeEnd.1.json
When a gapless database has an ayah with value 999, the app crashes
> Fixes a crash in QuranAudioPlayer

- Package.swift
- Sources/Localization/Resources/ar.lproj/Localizable.strings
- Sources/Localization/Resources/en.lproj/Localizable.strings
- Sources/Localization/Resources/tr.lproj/Localizable.strings
- Sources/QuranAudioKit/Preferences/AudioPreferences.swift
- Sources/QuranAudioKit/Reciter/RecentRecitersService.swift
- Tests/QuranAudioKitTests/RecentRecitersServiceTests.swift
> Add support for 'Recent Reciters' feature

- Sources/Localization/Resources/ar.lproj/Localizable.strings
- Sources/Localization/Resources/en.lproj/Localizable.strings
> 'Play' subtext not correct when multiple ayahs selected

- Sources/Localization/Resources/ar.lproj/Localizable.strings
- Sources/Localization/Resources/en.lproj/Localizable.strings
- Sources/Localization/Resources/tr.lproj/Localizable.strings
- Sources/QuranAudioKit/Reciter/DownloadedRecitersService.swift
- Tests/QuranAudioKitTests/DownloadedRecitersServiceTests.swift
The reciters list will now show the following sections:
- (coming soon) Search Bar
- Up to 3 recently played reciters
- All downloaded reciters (excluding the ones from the recent list)
- All English reciters
- All Arabic reciters
> Restructure the Reciters List to include Downloaded Reciters

- Sources/Localization/Resources/ar.lproj/Localizable.strings
- Sources/Localization/Resources/de.lproj/Localizable.strings
- Sources/Localization/Resources/en.lproj/Localizable.strings
- Sources/Localization/Resources/es.lproj/Localizable.strings
- Sources/Localization/Resources/fa.lproj/Localizable.strings
- Sources/Localization/Resources/fr.lproj/Localizable.strings
- Sources/Localization/Resources/kk.lproj/Localizable.strings
- Sources/Localization/Resources/ms.lproj/Localizable.strings
- Sources/Localization/Resources/my.lproj/Localizable.strings
- Sources/Localization/Resources/nl.lproj/Localizable.strings
- Sources/Localization/Resources/ru.lproj/Localizable.strings
- Sources/Localization/Resources/tr.lproj/Localizable.strings
- Sources/Localization/Resources/uz.lproj/Localizable.strings
This change allows the user the ability to easily repeat selected verse(s). Currently: 
1. If you want to repeat multiple selected verses, you have to select the verses, click on "Play selected ayahs", navigate to audio options on the bottom right, click on "loop" in "Play set of verses" and then click on the Play button. 
2. If you want to repeat only one selected verse, you have to select multiple verses first, click on "Play selected ayahs", navigate to audio options on the bottom right, change the end verse to be the same as the start verse, then click on "loop" in "Play set of verses", then click on the Play button.
This change allows repeating one or more verses with a single menu item press after selecting the verse(s).
**Single Verse Selected**
**Multiple Verses Selected**
> Add ayah menu item to allow playing selected verses in a loop

- Sources/QuranAudioKit/AudioPlayer/GaplessAudioRequestBuilder.swift
- Sources/QuranAudioKit/AudioPlayer/GappedAudioRequestBuilder.swift
- Tests/QuranAudioKitTests/GaplessAudioRequestBuilderTests.swift
- Tests/QuranAudioKitTests/GappedAudioRequestBuilderTests.swift
- Tests/QuranAudioKitTests/QuranAudioPlayerTests.swift
- Tests/QuranAudioKitTests/Reciter+Fixture.swift
- Tests/QuranAudioKitTests/Reciter+Preperation.swift
- Tests/QuranAudioKitTests/__Snapshots__/QuranAudioPlayerTests/testDownloadFirstBeforePlaying.1.json
- Tests/QuranAudioKitTests/__Snapshots__/QuranAudioPlayerTests/testPlayingDownloadedGaplessReciter1FullSura.1.json
- Tests/QuranAudioKitTests/__Snapshots__/QuranAudioPlayerTests/testPlayingDownloadedGaplessReciter1SuraEndsEarly.1.json
- Tests/QuranAudioKitTests/__Snapshots__/QuranAudioPlayerTests/testPlayingDownloadedGaplessReciter1SurasHasEndTimestamp.1.json
- Tests/QuranAudioKitTests/__Snapshots__/QuranAudioPlayerTests/testPlayingDownloadedGaplessReciter1SurasHasEndTimestampStopBeforeEnd.1.json
- Tests/QuranAudioKitTests/__Snapshots__/QuranAudioPlayerTests/testPlayingDownloadedGaplessReciter2Suras1stSuraHasEndTimestamp.1.json
- Tests/QuranAudioKitTests/__Snapshots__/QuranAudioPlayerTests/testPlayingDownloadedGaplessReciter3FullSura.1.json
It avoids reciting bismillah during a repeat. But ensures bismillah is recited when played across multiple suras.
> Avoids bismillah on repeat of the first ayah of surah - #409

- README.md
Update Readme with a more accurate diacritic mark for the Arabic letter hamza
> Update Readme with a more accurate diacritic mark

- Sources/Localization/Resources/vi.lproj/Localizable.strings
Can you help me check if it works? I don't have a mac or iPhone. thanks.
> Vietnamese Language Localization ios

- .swiftpm/xcode/xcshareddata/xcschemes/QuranEngine-Package.xcscheme
- AllTargetsTests/Empty.swift
- Package.swift
- QuranEngine-Package.xctestplan
> Create an empty AllTargets tests to produce coverage for untested code

- Package.swift
Add validation against repeating such a mistake again.
> Remove TestResources from the QuranEngine targets 

- Package.swift
Consistent package names avoid any SPM errors in CI/CD pipelines. https://stackoverflow.com/a/63079910/3077444
> Update package.swift file

- Example/QuranEngineApp.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Package.swift
This will fix the compilation errors ان شاء اللہ تَعَالٰی
> Point to version 3.1.3 of GenericDataSource

- Core/Localization/Resources/ar.lproj/Localizable.strings
- Core/Localization/Resources/de.lproj/Localizable.strings
- Core/Localization/Resources/en.lproj/Localizable.strings
- Core/Localization/Resources/es.lproj/Localizable.strings
- Core/Localization/Resources/fa.lproj/Localizable.strings
- Core/Localization/Resources/fr.lproj/Localizable.strings
- Core/Localization/Resources/kk.lproj/Localizable.strings
- Core/Localization/Resources/ms.lproj/Localizable.strings
- Core/Localization/Resources/nl.lproj/Localizable.strings
- Core/Localization/Resources/pt.lproj/Localizable.strings
- Core/Localization/Resources/ru.lproj/Localizable.strings
- Core/Localization/Resources/tr.lproj/Localizable.strings
- Core/Localization/Resources/ug.lproj/Localizable.strings
- Core/Localization/Resources/uz.lproj/Localizable.strings
- Core/Localization/Resources/vi.lproj/Localizable.strings
- Core/Localization/Resources/zh.lproj/Localizable.strings
GSheetStringsSyncer: https://github.com/mohamede1945/GSheetStringsSyncer
Sheet: https://docs.google.com/spreadsheets/d/1hqhbv19ohkUCfFp0u0hiva1aGqVIUIboR4_8Y5_IUng
> Synchronize to a Google Sheet using GSheetStringsSyncer

- Core/Localization/Resources/de.lproj/Localizable.strings
- Core/Localization/Resources/en.lproj/Localizable.strings
- Core/Localization/Resources/es.lproj/Localizable.strings
- Core/Localization/Resources/fa.lproj/Localizable.strings
- Core/Localization/Resources/fr.lproj/Localizable.strings
- Core/Localization/Resources/kk.lproj/Localizable.strings
- Core/Localization/Resources/ms.lproj/Localizable.strings
- Core/Localization/Resources/nl.lproj/Localizable.strings
- Core/Localization/Resources/pt.lproj/Localizable.strings
- Core/Localization/Resources/ru.lproj/Localizable.strings
- Core/Localization/Resources/tr.lproj/Localizable.strings
- Core/Localization/Resources/ug.lproj/Localizable.strings
- Core/Localization/Resources/uz.lproj/Localizable.strings
- Core/Localization/Resources/vi.lproj/Localizable.strings
- Core/Localization/Resources/zh.lproj/Localizable.strings
Generated ChatGPT translations file: [chatgpt-translations.json](https://github.com/quran/quran-ios/files/13405490/chatgpt-translations.json)
> Translate missing localization using ChatGPT 4.5

- Domain/ReadingService/Sources/ReadingResourcesService.swift
- Features/SettingsFeature/SettingsRootViewModel.swift
- UI/NoorUI/Components/List/NoorListItem.swift
- UI/NoorUI/Components/MultipartText.swift
- UI/UIx/UIKit/Popover/PopoverPresenter.swift
See commit messages for the various fixes
> Various bug fixes for 2.2.3 release

- Features/NotesFeature/NotesBuilder.swift
- Features/NotesFeature/NotesViewController.swift
- Features/NotesFeature/NotesViewModel.swift
- UI/UIx/SwiftUI/Miscellaneous/EditController.swift
Adds a basic sharing feature to the Notes page.
https://github.com/user-attachments/assets/be99339a-08c8-4108-9cd7-19d790977dd3
> Add Sharing to Notes

- Example/QuranEngineApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Package.resolved
The issue is fixed with this PR (groue/GRDB.swift#1589), I am going to update the version to latest of GRDB released yesterday which is 6.29.2 ان شاء اللہ تَعَالٰی
Closes  #652
> Update GRDB.swift to fix an Xcode 16.0 Beta issue.

- UI/UIx/SwiftUI/Views/TextAlignmentModifier.swift
> Fix alignment on right-to-left languages in translation view

- Features/SettingsFeature/SettingsRootView.swift
We can add `-DQURAN_SYNC` to "other swift flags" to enable it.
> Put Login with Quran.com behind a compiler flag
