- Quran/SqliteLastPagesPersistence.swift
Fix duplicate pages by making pages unique, and by using `replace into` instead of
`insert into`.
> Fix duplicate last pages

- .gitignore
- Quran.xcodeproj/project.pbxproj
- Quran.xcworkspace/contents.xcworkspacedata
- Quran/Info.plist
- fastlane/Fastfile
Fastlane integration to automate build uploads to TestFlight and replacing fabric keys. It also automates version changes.
When working on a new version we should execute:
```shell
fastlane version_reset verstion:1.1
```
When uploading a new version to test flight we should execute:
```shell
fastlane beta
```
we can execute once and then if there are some bug fixes, we do it and execute it again, it automatically increases the build number as long as we didn't submit the version to the app store.
There is an `Appfile` that should be placed next to `Fastfile` for the `beta` command to run, it shouldn't be shared in the repo. I'll e-mail it to you @ahmedre.
> Fastlane Integration + Incrementing version number

- Quran.xcodeproj/project.pbxproj
- Quran/LastPage.swift
- Quran/LastPageUpdater.swift
- Quran/QuranViewController.swift
- Quran/SQLiteLastPagesPersistence.swift
It fixes 2 issues:
1. User has 2 last pages, and then open the 2nd one and then close it. It still stays at the bottom.
2. [Device Only] If there is a last page bookmark open it, navigate to the next page and back again, close the quran page, you will see the last pages bookmark totally disappear.
> Fixes an issue that can make last pages not updated or delete them all at once

- Quran/SQLiteAyahTextPersistence.swift
- Quran/SearchPresenter.swift
Fixes #250 
Using `<b>` tokens for both start and end then splitting the search term on `<b>` and constructing the `NSAttributedString` for individual substrings increases the performance significantly compared to assuming a generic HTML text.
> 250: Search Performance Improvement

- Quran.xcodeproj/project.pbxproj
- Quran/SQLiteAyahTextPersistence.swift
- Quran/SearchAutocompleteTableViewCell.swift
- Quran/SearchAutocompleteTableViewCell.xib
- Quran/SearchResultsDataSource.swift
- Quran/SearchResultsViewController.swift
- Quran/SearchService.swift
Fixes #169
*  Showing just a handful of words for autocomplete result instead of a full verse text.
* Ability to show multiple results from the same verse.
* Always show search term as first autocomplete result.
* Add a search icon on the left of each result, similar to how the new app store is doing it.
The updated look for the autocompletes
> Improve autocomplete results

- Quran/SearchPresenter.swift
Fixes #258 
This is mainly because an Arabic word will be split if part of it highlighted and the other part is not.
> 258: No highlights for Arabic autocomplete results

- Quran/SearchResultsDataSource.swift
- Quran/SearchResultsViewController.swift
- Quran/SearchViewController.swift
Fixes #209
* Adding a cancel button
* Same background for both the result and the entire view.
* Default `UISearchBar` appearance for old and latest iOS.
* Set a fixed separator inset which improves the separator inset for empty rows.
> Search UI Similar to New App Store Search UI

- Quran/TranslationPageLayoutOperation.swift
Fixes #281.
Translation text was getting trimmed for some languages that requires `NSLayoutManager.ensureLayout` to be called before getting `NSLayoutManager.numberOfGlyphs` as `numberOfGlyphs` would get an underestimated value if called first.
> 281: Fix translation text gets trimmed

- Quran/PhonePopoverPresentationControllerDelegate.swift
- Quran/QariTableViewControllerCreator.swift
- Quran/QuranViewController.swift
Fixes #292 
Using the iOS 8.3 API:
```swift   
optional func adaptivePresentationStyle(for controller: UIPresentationController,
traitCollection: UITraitCollection) -> UIModalPresentationStyle
```
> 292: Fix popover for new iPhones iPhone XR & iPhone X Max

- Quran.xcodeproj/project.pbxproj
- Quran/WordPointerInteractor.swift
- Quran/WordPointerViewController.swift
- UIKitExtension/UIImage+Extension.swift
This is an attempt at fixing #211. The code shows an image of the word next to the text in the popover.
This solution needs at least iOS 10.0 to work.
Some Issues that I couldn't solve:
* The image that gets displayed is somewhat small, due to limitations in the Popover pod
* It quite a few calculations every time the function is called, not resource friendly
* Not tested on a real device
[Video](https://youtu.be/39pVtjO1Xpk)
> fix #211: shows image next to translation

- Sources/QuranKit/AyahNumber.swift
- Sources/QuranKit/LazyAtomic.swift
- Sources/QuranKit/Page.swift
- Sources/QuranKit/Quran.swift
- Sources/QuranKit/Util.swift
- Tests/QuranKitTests/AyahNumberTests.swift
- Tests/QuranKitTests/PageTests.swift
- Tests/QuranKitTests/QuarterTests.swift
- Tests/QuranKitTests/SuraTests.swift
* Using final class for the Quran object.
* Cache pages, suras, juzs, hizbs in the Quran object.
* Use binary search to find juz' of a page and page of a verse.
This improved reading juzs for all suras time from 8s to 0.001s.
> Improve the performance of QuranKit

- Sources/TranslationService/ActiveTranslationsPersistence.swift
- Sources/TranslationService/TranslationsRepository.swift
As id field can be different between different translation versions.
> Use filename to identify translation

- Features/AudioBannerFeature/AudioBannerViewController.swift
- Features/AudioBannerFeature/AudioBannerViewModel.swift
- Features/AudioBannerFeature/AudioReciterBarView.swift
- Features/AudioBannerFeature/AudioReciterBarView.xib
Currently, in order to change any of the advanced audio options, you first need to hit the play button. This change displays the advanced audio options button on the reciter bar so you can change the audio settings without hitting play first. 
**Before and After:**
> Always show advanced audio options button

- Domain/TranslationService/Sources/TranslationsRepository.swift
- Domain/TranslationService/Tests/TranslationsRepositoryTests.swift
This pull request reverts a recent change (https://github.com/quran/quran-ios/pull/526) in the matching logic of translations from using `Translation.Id` to `fileName`. The update was initially implemented to enhance the accuracy of translation matching. However, it was observed that new versions of the same translation are assigned new IDs, leading to inconsistencies in the matching process.
After updating the matching logic to utilize `Translation.Id`, we encountered a significant issue where new versions of translations received different IDs, breaking the expected continuity and leading to mismatches in our application. This behavior was not anticipated and has affected the stability of the translation matching feature.
To address this, we've decided to revert to using the `fileName` …
> Revert Translation Matching Logic to Use FileName

- Core/Localization/Resources/ar.lproj/Localizable.strings
- Core/Localization/Resources/en.lproj/Localizable.strings
- Core/Localization/Resources/nl.lproj/Localizable.strings
- Core/Localization/Resources/vi.lproj/Localizable.strings
- Features/ReadingSelectorFeature/ReadingSelectorViewModel.swift
- Features/ReadingSelectorFeature/View/Reading+Resources.swift
- Features/ReadingSelectorFeature/View/ReadingInfo.swift
Changes:
- Transitioned property creation from localization-based to code-based implementation.
- Resolved issue that Tajweed Mushaf mistakenly supports word-by-word translation.
> Refactor property reading: use code-based creation

- Core/Utilities/Sources/Features/AsyncInitializer.swift
- Data/BatchDownloader/Sources/Downloader/DownloadBatchDataController.swift
- Data/BatchDownloader/Sources/Downloader/DownloadManager.swift
- Data/BatchDownloader/Tests/DownloadManagerTests.swift
- Data/BatchDownloaderFake/BatchDownloaderFake.swift
Sometimes `DownloadManager.getOnGoingDownloads` may be called earlier than `DownloadManager.start`. This result in a crash.
This change ensures that getOnGoingDownloads awaits the initialization.
> Fix crash when getOnGoingDownloads is called early

- Data/BatchDownloader/Sources/Downloader/DownloadBatchDataController.swift
- Data/BatchDownloader/Sources/Downloader/DownloadManager.swift
- Features/AudioBannerFeature/AudioBannerViewModel.swift
- Features/WordPointerFeature/WordPointerViewController.swift
- Features/WordPointerFeature/WordPointerViewModel.swift
This fixes the issue when audio banner not in a functioning state.
> Select first reciter if no match found with the stored reciter id

- Example/QuranEngineApp.xcodeproj/project.pbxproj
> Remove Hafs 1405 from being on-demand resources

- Features/SearchFeature/SearchViewController.swift
Apparently, UIHostingController takes over the responsibility of the `navigationItem` on iOS 14.
> Fix search bar disappearance on iOS 14

- Core/AppMigrator/Sources/AppVersionUpdater.swift
- Core/Preferences/Preference.swift
- Core/Preferences/Preferences.swift
- Domain/AudioUpdater/Sources/AudioUpdatePreferences.swift
- Domain/QuranTextKit/Sources/Search/Recents/SearchRecentsService.swift
- Domain/QuranTextKit/Tests/SearchRecentsServiceTests.swift
- Domain/ReciterService/Sources/ReciterPreferences.swift
- Domain/ReciterService/Tests/RecentRecitersServiceTests.swift
- Domain/TranslationService/Sources/SelectedTranslationsPreferences.swift
- Features/SettingsFeature/Diagnostics/DiagnosticsService.swift
- Package.resolved
Make Preferences is the only way to CRUD user defaults and use custom observation in Preferences class.
> Fix observation of UserDefaults

- Features/SearchFeature/SearchTypes.swift
- Features/SearchFeature/SearchView.swift
- Features/SearchFeature/SearchViewController.swift
- Features/SearchFeature/SearchViewModel.swift
This change ensures only one search request executes at a time. Additionally, the change ensures proper search lifecycle handling.
> Search was broken due to concurrent search requests

- Features/TranslationsFeature/TranslationsListViewModel.swift
This is currently being handled at the ViewModel level, but I could see this being done by `TranslationsDownloader` as well.
Fixes #206 .
> Select newly downloaded translation

- Features/ReadingSelectorFeature/View/ReadingDetails.swift
- Features/ReadingSelectorFeature/View/ReadingInfo.swift
Some users don't understand they need to tap "set as current Mushaf" to change the current mushaf.
> Add set as current Mushaf to the top of the details screen

- Domain/QuranTextKit/Sources/ShareableText/ShareableVerseTextRetriever.swift
- Domain/QuranTextKit/Tests/ShareableVerseTextRetrieverTests.swift
- Features/NotesFeature/NotesViewModel.swift
Tries to fix the issue with brackets in texts with bidirectional languages by nesting the arabic text with unicode characters
Based off of these [Apple Docs](https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPInternational/SupportingRight-To-LeftLanguages/SupportingRight-To-LeftLanguages.html#//apple_ref/doc/uid/10000171i-CH17-SW11)
and this [Stack Overflow](https://stackoverflow.com/questions/37497610/ios-rtl-improperly-displaying-english-inside-rtl-string)
https://github.com/user-attachments/assets/45397e0b-3844-495f-8933-ae590ffb4a88
> Fix Arabic Text Rendering in Notes Sharing

- Example/QuranEngineApp/Classes/AppDelegate.swift
- Example/QuranEngineApp/Classes/Container.swift
- Example/QuranEngineApp/Classes/SceneDelegate.swift
- Example/QuranEngineApp/Info.plist
- Features/AppStructureFeature/Launch/LaunchBuilder.swift
Implemented custom url scheme to support launching the Quran Application from outside the application
For example, enter this in browser `quran-ios://` and it will redirect you to the Quran Application
Example Video
https://github.com/user-attachments/assets/cafcc9f4-5c24-4ebd-b6fb-1b680ab69f7c
> Custom URL Scheme Implementation

- Domain/QuranTextKit/Sources/Preferences/FontSizePreferences.swift
- Model/QuranText/FontSize.swift
- UI/NoorUI/Features/MoreMenu/components/MoreMenuFontSize.swift
- UI/NoorUI/Font/FontName++.swift
- UI/NoorUI/Font/FontSize++.swift
- Increase the default quran font size from 17 to 21.
- Add more font sizes that matches [DynamicTypeSize](https://developer.apple.com/documentation/swiftui/dynamictypesize)
> Increase the default Quran font size in translation UI 

- Core/Localization/NumberFormatter+Extension.swift
- Features/AyahMenuFeature/AyahMenuViewModel.swift
- Features/NotesFeature/NotesViewModel.swift
1.  Fixes #666, 
I think maybe Apple changed the locale keys in the new update ? The docs say it uses [BCP-47](https://developer.apple.com/documentation/foundation/locale/2293563-init). So updated the string to use [this](https://www.techonthenet.com/js/language_tags.php).
2. Refactors the sharing abit to make it more consistent, since sometimes English and Arabic would be on the same line, now we add newlines properly I think.
3. Updates the ayah sharing to use the same logic as [copy](https://github.com/quran/quran-ios/blob/c40fb5c958ff0f572e085e1b1ec67c716b68ca78/Features/AyahMenuFeature/AyahMenuViewModel.swift#L136-L145). Before copy would have newlines and sharing didn't but now they should both have it.
<div style="display: flex; gap: 10px;">
</div>
> Fix Arabic Number Bug and Improve Notes Sharing

- Data/OAuthClient/Sources/AppAuthOAuthClient.swift
- Data/OAuthClient/Sources/OAuthClient.swift
- Domain/QuranProfileService/Sources/QuranProfileService.swift
- Example/QuranEngineApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Example/QuranEngineApp/Classes/Container.swift
- Features/AppDependencies/AppDependencies.swift
- Features/SettingsFeature/SettingsBuilder.swift
- Features/SettingsFeature/SettingsRootView.swift
- Features/SettingsFeature/SettingsRootViewModel.swift
- Package.swift
Introduces the basic infra for authenticating the user to their Quran.com account, and the basic UI for login. Will be expanded upon in following tasks.
- `Data/OAuthClient` handles the actual request. This is the _starting point_ to handle authenticating requests and refreshing the tokens. The persistance of the tokens is yet to be handled. 
- `Domain/QuranProfileService` is the service counterpart. Will, probably, only expose the profile information. 
- `openid/AppAuth-iOS` was added as a dependency. Cuts down on much nuisance in OpenID communications.
> OAuth Support
